#!/bin/bash

if [ -z "${JAVA}" ] ; then
JAVA=java 
fi

versionlines=`java -version 2> \
>(grep 'java version' | awk '{print $0}')`
version=`tr -d "\"[:alpha:]"  <<<$versionlines`
echo Your Java version is $version
if [ $(echo $version | grep -e '1.8') ]; then
    echo "Yes, we can do ANISOtime."
else
    echo "It cannot run ANISOtime."
echo "Get the latest Java from Oracle."
echo "http://www.oracle.com/technetwork/java/javase/downloads/index.html"
fi



